---------------
---- THEME ----
---------------

-- Colors generated by `ze theme set`, loaded last so they win over looknfeel.
-- Missing on a fresh install until the first theme is applied, hence the pcall.
pcall(dofile, os.getenv("HOME") .. "/.config/ze/current/theme/hyprland.lua")
