/* Recolour Adwaita with the theme palette. GTK3 uses the theme_* names, libadwaita (GTK4) the rest. */

@define-color accent_color {{ accent }};
@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ background }};
@define-color destructive_color {{ red }};
@define-color destructive_bg_color {{ red }};
@define-color destructive_fg_color {{ background }};
@define-color success_color {{ green }};
@define-color warning_color {{ yellow }};
@define-color error_color {{ red }};

@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};
@define-color view_bg_color {{ lighter_background }};
@define-color view_fg_color {{ foreground }};
@define-color headerbar_bg_color {{ dark_background }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ muted }};
@define-color headerbar_backdrop_color {{ dark_background }};
@define-color headerbar_shade_color alpha({{ darker_background }}, 0.5);
@define-color sidebar_bg_color {{ dark_background }};
@define-color sidebar_fg_color {{ foreground }};
@define-color sidebar_backdrop_color {{ dark_background }};
@define-color sidebar_border_color {{ muted }};
@define-color secondary_sidebar_bg_color {{ dark_background }};
@define-color secondary_sidebar_fg_color {{ foreground }};
@define-color card_bg_color {{ lighter_background }};
@define-color card_fg_color {{ foreground }};
@define-color card_shade_color alpha({{ darker_background }}, 0.5);
@define-color dialog_bg_color {{ background }};
@define-color dialog_fg_color {{ foreground }};
@define-color popover_bg_color {{ lighter_background }};
@define-color popover_fg_color {{ foreground }};
@define-color thumbnail_bg_color {{ lighter_background }};
@define-color thumbnail_fg_color {{ foreground }};
@define-color shade_color alpha({{ darker_background }}, 0.36);
@define-color scrollbar_outline_color alpha({{ foreground }}, 0.1);
@define-color borders {{ muted }};

@define-color theme_bg_color {{ background }};
@define-color theme_fg_color {{ foreground }};
@define-color theme_base_color {{ lighter_background }};
@define-color theme_text_color {{ foreground }};
@define-color theme_selected_bg_color {{ accent }};
@define-color theme_selected_fg_color {{ background }};
@define-color theme_unfocused_bg_color {{ background }};
@define-color theme_unfocused_fg_color {{ light_foreground }};
@define-color theme_unfocused_base_color {{ lighter_background }};
@define-color theme_unfocused_text_color {{ light_foreground }};
@define-color theme_unfocused_selected_bg_color {{ selection }};
@define-color theme_unfocused_selected_fg_color {{ foreground }};
@define-color insensitive_bg_color {{ background }};
@define-color insensitive_fg_color {{ muted }};
@define-color insensitive_base_color {{ lighter_background }};
@define-color unfocused_insensitive_color {{ muted }};
@define-color unfocused_borders {{ muted }};
@define-color wm_title {{ foreground }};
@define-color wm_unfocused_title {{ light_foreground }};
@define-color wm_bg {{ dark_background }};
@define-color wm_unfocused_bg {{ dark_background }};
