{
  "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
  "name": "Ze",
  "author": "ze theme set",
  "themes": [
    {
      "name": "Ze",
      "appearance": "{{ mode }}",
      "style": {
        "background": "{{ background }}",
        "surface.background": "{{ dark_background }}",
        "elevated_surface.background": "{{ lighter_background }}",
        "element.background": "{{ lighter_background }}",
        "element.hover": "{{ mix lighter_background foreground 8% }}",
        "element.active": "{{ selection }}",
        "element.selected": "{{ selection }}",
        "element.disabled": "{{ dark_background }}",
        "ghost_element.hover": "{{ mix background foreground 6% }}",
        "ghost_element.active": "{{ selection }}",
        "ghost_element.selected": "{{ selection }}",
        "drop_target.background": "{{ mix background accent 25% }}",
        "border": "{{ muted }}",
        "border.variant": "{{ mix background muted 50% }}",
        "border.focused": "{{ accent }}",
        "border.selected": "{{ accent }}",
        "border.transparent": "#00000000",
        "border.disabled": "{{ dark_background }}",
        "text": "{{ foreground }}",
        "text.muted": "{{ light_foreground }}",
        "text.placeholder": "{{ muted }}",
        "text.disabled": "{{ muted }}",
        "text.accent": "{{ accent }}",
        "icon": "{{ foreground }}",
        "icon.muted": "{{ light_foreground }}",
        "icon.disabled": "{{ muted }}",
        "icon.placeholder": "{{ muted }}",
        "icon.accent": "{{ accent }}",
        "status_bar.background": "{{ dark_background }}",
        "title_bar.background": "{{ dark_background }}",
        "title_bar.inactive_background": "{{ dark_background }}",
        "toolbar.background": "{{ background }}",
        "tab_bar.background": "{{ dark_background }}",
        "tab.inactive_background": "{{ dark_background }}",
        "tab.active_background": "{{ background }}",
        "panel.background": "{{ dark_background }}",
        "panel.focused_border": "{{ accent }}",
        "pane.focused_border": "{{ accent }}",
        "scrollbar.thumb.background": "{{ mix background foreground 20% }}",
        "scrollbar.thumb.hover_background": "{{ mix background foreground 35% }}",
        "scrollbar.thumb.border": "{{ mix background foreground 20% }}",
        "scrollbar.track.background": "#00000000",
        "scrollbar.track.border": "{{ mix background muted 50% }}",
        "editor.background": "{{ background }}",
        "editor.foreground": "{{ foreground }}",
        "editor.gutter.background": "{{ background }}",
        "editor.subheader.background": "{{ dark_background }}",
        "editor.active_line.background": "{{ mix background foreground 5% }}",
        "editor.highlighted_line.background": "{{ mix background accent 12% }}",
        "editor.line_number": "{{ muted }}",
        "editor.active_line_number": "{{ foreground }}",
        "editor.invisible": "{{ muted }}",
        "editor.wrap_guide": "{{ mix background muted 50% }}",
        "editor.active_wrap_guide": "{{ muted }}",
        "editor.document_highlight.read_background": "{{ mix background accent 15% }}",
        "editor.document_highlight.write_background": "{{ mix background accent 25% }}",
        "search.match_background": "{{ mix background yellow 35% }}",
        "terminal.background": "{{ background }}",
        "terminal.foreground": "{{ foreground }}",
        "terminal.bright_foreground": "{{ bright_foreground }}",
        "terminal.dim_foreground": "{{ light_foreground }}",
        "terminal.ansi.black": "{{ background }}",
        "terminal.ansi.red": "{{ red }}",
        "terminal.ansi.green": "{{ green }}",
        "terminal.ansi.yellow": "{{ yellow }}",
        "terminal.ansi.blue": "{{ blue }}",
        "terminal.ansi.magenta": "{{ magenta }}",
        "terminal.ansi.cyan": "{{ cyan }}",
        "terminal.ansi.white": "{{ foreground }}",
        "terminal.ansi.bright_black": "{{ muted }}",
        "terminal.ansi.bright_red": "{{ bright_red }}",
        "terminal.ansi.bright_green": "{{ bright_green }}",
        "terminal.ansi.bright_yellow": "{{ bright_yellow }}",
        "terminal.ansi.bright_blue": "{{ bright_blue }}",
        "terminal.ansi.bright_magenta": "{{ bright_magenta }}",
        "terminal.ansi.bright_cyan": "{{ bright_cyan }}",
        "terminal.ansi.bright_white": "{{ bright_foreground }}",
        "link_text.hover": "{{ accent }}",
        "conflict": "{{ yellow }}",
        "conflict.background": "{{ mix background yellow 15% }}",
        "created": "{{ green }}",
        "created.background": "{{ mix background green 15% }}",
        "deleted": "{{ red }}",
        "deleted.background": "{{ mix background red 15% }}",
        "modified": "{{ yellow }}",
        "modified.background": "{{ mix background yellow 15% }}",
        "renamed": "{{ blue }}",
        "hidden": "{{ muted }}",
        "ignored": "{{ muted }}",
        "info": "{{ blue }}",
        "info.background": "{{ mix background blue 15% }}",
        "hint": "{{ cyan }}",
        "hint.background": "{{ mix background cyan 15% }}",
        "warning": "{{ yellow }}",
        "warning.background": "{{ mix background yellow 15% }}",
        "error": "{{ red }}",
        "error.background": "{{ mix background red 15% }}",
        "success": "{{ green }}",
        "success.background": "{{ mix background green 15% }}",
        "unreachable": "{{ muted }}",
        "predictive": "{{ muted }}",
        "players": [
          { "cursor": "{{ bright_foreground }}", "background": "{{ accent }}", "selection": "{{ mix background accent 35% }}" },
          { "cursor": "{{ green }}", "background": "{{ green }}", "selection": "{{ mix background green 35% }}" },
          { "cursor": "{{ magenta }}", "background": "{{ magenta }}", "selection": "{{ mix background magenta 35% }}" },
          { "cursor": "{{ yellow }}", "background": "{{ yellow }}", "selection": "{{ mix background yellow 35% }}" }
        ],
        "syntax": {
          "attribute": { "color": "{{ yellow }}" },
          "boolean": { "color": "{{ orange }}" },
          "comment": { "color": "{{ muted }}", "font_style": "italic" },
          "comment.doc": { "color": "{{ dark_foreground }}", "font_style": "italic" },
          "constant": { "color": "{{ orange }}" },
          "constructor": { "color": "{{ yellow }}" },
          "embedded": { "color": "{{ foreground }}" },
          "emphasis": { "font_style": "italic" },
          "emphasis.strong": { "font_weight": 700 },
          "enum": { "color": "{{ yellow }}" },
          "function": { "color": "{{ blue }}" },
          "function.method": { "color": "{{ blue }}" },
          "hint": { "color": "{{ cyan }}" },
          "keyword": { "color": "{{ magenta }}" },
          "label": { "color": "{{ accent }}" },
          "link_text": { "color": "{{ accent }}", "font_style": "italic" },
          "link_uri": { "color": "{{ cyan }}" },
          "number": { "color": "{{ orange }}" },
          "operator": { "color": "{{ cyan }}" },
          "predictive": { "color": "{{ muted }}", "font_style": "italic" },
          "preproc": { "color": "{{ magenta }}" },
          "primary": { "color": "{{ foreground }}" },
          "property": { "color": "{{ foreground }}" },
          "punctuation": { "color": "{{ light_foreground }}" },
          "punctuation.bracket": { "color": "{{ light_foreground }}" },
          "punctuation.delimiter": { "color": "{{ light_foreground }}" },
          "punctuation.list_marker": { "color": "{{ accent }}" },
          "punctuation.special": { "color": "{{ red }}" },
          "string": { "color": "{{ green }}" },
          "string.escape": { "color": "{{ cyan }}" },
          "string.regex": { "color": "{{ orange }}" },
          "string.special": { "color": "{{ orange }}" },
          "string.special.symbol": { "color": "{{ orange }}" },
          "tag": { "color": "{{ red }}" },
          "text.literal": { "color": "{{ green }}" },
          "title": { "color": "{{ accent }}", "font_weight": 700 },
          "type": { "color": "{{ yellow }}" },
          "variable": { "color": "{{ foreground }}" },
          "variable.special": { "color": "{{ red }}" },
          "variant": { "color": "{{ yellow }}" }
        }
      }
    }
  ]
}
